#!/usr/bin/env python3
"""Train the BY_ML split-ordering model and emit ml_order_model.h for radiobase.c.

This is the regeneration step for the header radiobase.c #includes to score candidates at
level 0 of a size==1 state (see docs/status.md's radius-mode/ordering thread, 2026-08-24). The
feature function and model shape are duplicated from tools/ml/recursive_value.py's feat()/
deficit() rather than imported, because that module runs its own load()/main() at import time
against /tmp paths that no longer exist here -- keep the two in sync by hand if either changes,
same convention recursive_value.py itself uses for value_level_transfer.py.

Two things this script does that recursive_value.py's own experiment_1 did not:
  1. Reproduces the ORIGINAL held-out check (train k in {4,5,6}, test k=7) first, as a regression
     gate -- if this AUC drifts from the documented 0.986, something about the data or feature
     code has changed and the export should not proceed silently.
  2. Trains the FINAL embedded model on all four levels (4,5,6,7) combined, since there is no
     longer a reason to hold k=7 out once the holdout check above has passed -- more data for a
     model that will be asked to extrapolate to k=8/9, which none of the training levels reach.

Usage: tools/ml/export_ordering_model.py [--out radiobase_ml_order_model.h]
"""
import argparse
import csv
import sys
from collections import defaultdict
from pathlib import Path

import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.metrics import roc_auc_score

REPO = Path(__file__).resolve().parents[2]

# ---- duplicated from tools/ml/recursive_value.py (feat/deficit/NAMES) -- keep in sync by hand.
MAXN1 = defaultdict(dict)
for row in csv.DictReader(open(REPO / "data/pareto_sb.csv")):
    try:
        k, m, n1 = int(row["k"]), int(row["m"]), int(row["n1"])
    except (ValueError, KeyError):
        continue
    if row.get("bound") == "max":
        MAXN1[k][m] = max(MAXN1[k].get(m, 0), n1)


def deficit(parts, k):
    if not parts:
        return -1.0
    return max(n - MAXN1.get(k, {}).get(m, 0) for n, m in ((max(a, b), min(a, b)) for a, b in parts))


def feat(parts, k):
    C = 3.0 ** k
    R = C ** 0.5
    if not parts:
        return [0.0, 0.0] + [0.0] * 24 + [-1.0, 0.0, 1.0, 0.0, 0.0]
    n = np.array([max(a, b) for a, b in parts], float)
    m = np.array([min(a, b) for a, b in parts], float)
    area = n * m / C
    nn = n / R
    mm = m / R
    asp = n / np.maximum(m, 1)

    def pool(v):
        s = np.sort(v)
        return [v.sum(), v.mean(), s[-1], s[0], v.std(), s[len(s) // 2]]

    f = [float(len(parts)), area.sum()]
    for v in (area, nn, mm, asp):
        f += pool(v)
    d = deficit(parts, k)
    f += [d / R, float(d > 0), 1.0 - area.sum(), float(np.sort(area)[-1]),
          float(np.sort(area)[-1] / max(area.sum(), 1e-9))]
    return f


NAMES = (["nparts", "mass"]
         + [f"{v}_{p}" for v in ("area", "n", "m", "asp") for p in ("sum", "mean", "max", "min", "std", "med")]
         + ["deficit", "violated", "headroom", "maxarea", "maxshare"])
# ---- end duplicated block


def load(k, nparts=4):
    X, y = [], []
    path = (REPO / f"data/ml_order/labeled_k{k}.txt" if nparts == 4
            else REPO / f"data/ml_order/labeled_n{nparts}_k{k}.txt")
    for line in open(path):
        w = line.split()
        rc = int(w[0])
        if rc not in (0, 1):  # drop MAYBE -- never record it as either class
            continue
        v = [int(x) for x in w[1:]]
        parts = [(v[i], v[i + 1]) for i in range(0, len(v), 2)]
        X.append(feat(parts, k))
        y.append(1 if rc == 0 else 0)
    return np.array(X, np.float32), np.array(y)


def fit(levels, sizes=(4,)):
    Xs, ys = [], []
    for nparts in sizes:
        for k in levels:
            path = (REPO / f"data/ml_order/labeled_k{k}.txt" if nparts == 4
                    else REPO / f"data/ml_order/labeled_n{nparts}_k{k}.txt")
            if not path.exists():
                continue
            Xk, yk = load(k, nparts)
            Xs.append(Xk); ys.append(yk)
            print(f"  nparts={nparts} k={k}: {len(yk)} states, {yk.mean():.1%} solvable",
                  file=sys.stderr)
    return make_pipeline(StandardScaler(), LogisticRegression(max_iter=4000)).fit(
        np.concatenate(Xs), np.concatenate(ys))


def emit_header(out_path, scaler, clf, maxn1):
    kmax = max(maxn1) if maxn1 else 0
    mmax = max((m for d in maxn1.values() for m in d), default=0)
    table = [[-1] * (mmax + 1) for _ in range(kmax + 1)]
    for k, d in maxn1.items():
        for m, n1 in d.items():
            table[k][m] = n1

    lines = []
    lines.append("/* GENERATED by tools/ml/export_ordering_model.py -- do not hand-edit.")
    lines.append(" * Source data: data/ml_order/labeled_k{4,5,6,7}.txt (see data/ml_order/README.md)")
    lines.append(" *              and data/pareto_sb.csv (the MAXN1 deficit table below).")
    lines.append(" * Model: StandardScaler + LogisticRegression, trained on all of k in {4,5,6,7}.")
    lines.append(" * Feature order (ML_NFEAT entries), matching tools/ml/export_ordering_model.py's")
    lines.append(" * feat(): " + ", ".join(NAMES))
    lines.append(" */")
    lines.append("#ifndef ML_ORDER_MODEL_H")
    lines.append("#define ML_ORDER_MODEL_H")
    lines.append("")
    lines.append(f"#define ML_NFEAT {len(NAMES)}")
    lines.append("")

    def emit_array(name, vals):
        body = ", ".join(f"{v:.17g}" for v in vals)
        lines.append(f"static const double {name}[ML_NFEAT] = {{ {body} }};")

    emit_array("ml_scaler_mean", scaler.mean_)
    emit_array("ml_scaler_scale", scaler.scale_)
    emit_array("ml_coef", clf.coef_[0])
    lines.append(f"static const double ml_intercept = {clf.intercept_[0]:.17g};")
    lines.append("")
    lines.append(f"#define ML_MAXN1_KMAX {kmax}")
    lines.append(f"#define ML_MAXN1_MMAX {mmax}")
    lines.append("/* ml_maxn1[k][m] = proven max n1 solvable for Sb(n1:m) in k, from data/pareto_sb.csv's")
    lines.append("   own 'max' bound rows; -1 where no proven bound is recorded (deficit() then treats")
    lines.append("   the bound as 0, matching the Python default MAXN1.get(k,{}).get(m,0)). */")
    lines.append(f"static const int ml_maxn1[ML_MAXN1_KMAX + 1][ML_MAXN1_MMAX + 1] = {{")
    for row in table:
        lines.append("    { " + ", ".join(str(v) for v in row) + " },")
    lines.append("};")
    lines.append("")
    lines.append("#endif /* ML_ORDER_MODEL_H */")
    out_path.write_text("\n".join(lines) + "\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(REPO / "ml_order_model.h"))
    args = ap.parse_args()

    print("Regression gate: reproducing the documented k<={4,5,6}->k=7 holdout AUC "
          "(nparts=4 only, matching the original single-size measurement)", file=sys.stderr)
    holdout = fit([4, 5, 6], sizes=(4,))
    Xte, yte = load(7, 4)
    auc = roc_auc_score(yte, holdout.predict_proba(Xte)[:, 1])
    print(f"  holdout AUC = {auc:.5f} (documented: 0.986)", file=sys.stderr)
    if abs(auc - 0.986) > 0.02:
        print(f"REFUSING to export: holdout AUC {auc:.5f} drifted from the documented 0.986 by "
              f"more than 0.02 -- data or feature code has changed underneath this script.",
              file=sys.stderr)
        sys.exit(1)

    print("\nSecond gate: combined-vs-separate comparison across nparts in {1,2,3,4}, "
          "train k<=6 test k=7 (2026-08-24 finding: combined ties or beats separate on every "
          "size measured so far)", file=sys.stderr)
    combined_holdout = fit([4, 5, 6], sizes=(1, 2, 3, 4))
    for nparts in (1, 2, 3, 4):
        path = (REPO / "data/ml_order/labeled_k7.txt" if nparts == 4
                else REPO / f"data/ml_order/labeled_n{nparts}_k7.txt")
        if not path.exists():
            continue
        Xte_n, yte_n = load(7, nparts)
        if yte_n.mean() in (0.0, 1.0) or len(yte_n) < 20:
            print(f"  nparts={nparts}: test set degenerate/too small, skipping", file=sys.stderr)
            continue
        auc_n = roc_auc_score(yte_n, combined_holdout.predict_proba(Xte_n)[:, 1])
        print(f"  nparts={nparts}: combined-model AUC on k=7 = {auc_n:.4f}  (n={len(yte_n)})",
              file=sys.stderr)

    print("\nTraining the final embedded model on all of k in {4,5,6,7}, sizes in {1,2,3,4}",
          file=sys.stderr)
    final = fit([4, 5, 6, 7], sizes=(1, 2, 3, 4))
    scaler = final.named_steps["standardscaler"]
    clf = final.named_steps["logisticregression"]

    out_path = Path(args.out)
    emit_header(out_path, scaler, clf, MAXN1)
    print(f"wrote {out_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
